// GENERATED by gen.py from design/abilities.json - edit the sheet, not this file
pub struct Ability { pub id: &'static str, pub key: &'static str, pub cooldown_s: f32, pub stamina_cost: i32, pub distance_m: f32, pub duration_s: f32 }
pub const DASH: Ability = Ability { id: "dash", key: "dash", cooldown_s: 1.0, stamina_cost: 15, distance_m: 6.0, duration_s: 0.18 };
pub const DOUBLE_JUMP: Ability = Ability { id: "double_jump", key: "jump", cooldown_s: 0.0, stamina_cost: 10, distance_m: 2.2, duration_s: 0.35 };
pub const WALL_RUN: Ability = Ability { id: "wall_run", key: "jump", cooldown_s: 0.0, stamina_cost: 5, distance_m: 8.0, duration_s: 1.2 };
