#!/usr/bin/env python3
"""Generate plugin code from the design sheets (one row -> one struct). Runs preflight-independent parts only."""
import json, os
R = os.path.dirname(os.path.abspath(__file__))
VK = {"LeftAlt": 0xA4, "Space": 0x20, "F": 0x46, "V": 0x56, "B": 0x42, "N": 0x4E, "F6": 0x75}
rows = json.load(open(f"{R}/design/keys.json"))["rows"]
out = ["// GENERATED by gen.py from design/keys.json - edit the sheet, not this file",
       "pub struct Key { pub id: &'static str, pub name: &'static str, pub vk: u16 }",
       f"pub const KEYS: [Key; {len(rows)}] = ["]
for r in rows:
    if r["default"] not in VK: raise SystemExit(f"no VK code for {r['default']} (keys[{r['id']}])")
    out.append(f'    Key {{ id: "{r["id"]}", name: "{r["default"]}", vk: 0x{VK[r["default"]]:02X} }},')
out.append("];")
open(f"{R}/plugin/src/keys.rs", "w").write("\n".join(out) + "\n")
print(f"generated plugin/src/keys.rs ({len(rows)} keys)")

# abilities sheet -> one const struct per stage-1 row
ab = json.load(open(f"{R}/design/abilities.json"))["rows"]
o = ["// GENERATED by gen.py from design/abilities.json - edit the sheet, not this file",
     "pub struct Ability { pub id: &'static str, pub key: &'static str, pub cooldown_s: f32, pub stamina_cost: i32, pub distance_m: f32, pub duration_s: f32 }"]
for r in ab:
    if r["stage"] != 1: continue
    o.append(f'pub const {r["id"].upper()}: Ability = Ability {{ id: "{r["id"]}", key: "{r["key"]}", cooldown_s: {float(r["cooldown_s"])}, '
             f'stamina_cost: {int(r["stamina_cost"])}, distance_m: {float(r["distance_m"])}, duration_s: {float(r["duration_s"])} }};')
open(f"{R}/plugin/src/abilities.rs", "w").write("\n".join(o) + "\n")
print("generated plugin/src/abilities.rs")
